// auto-generated, run 'node scripts/lochex.mjs' to refresh
namespace microcode {
    export const lang = "de"
    export const font = bitmaps.font8
    export function resolveTooltip(id: string) {
        let res: string = ""
        if (!id) return id
        else if (id === "tagline") res = "für Calliope mini V3";
        else if (id === "sensors") res = "wenn...";
        else if (id === "actuators") res = "mache...";
        else if (id === "when") res = "wenn";
        else if (id === "do") res = "mache";
        else if (id === "connect") res = "verbinden";
        else if (id === "rule") res = "Regel";
        else if (id === "add_rule") res = "Regel hinzufügen";
        else if (id === "delete_rule") res = "Regel löschen";
        else if (id === "rule_up") res = "Regel nach oben verschieben";
        else if (id === "rule_down") res = "Regel nach unten verschieben";
        else if (id === "disk") res = "speichern";
        else if (id === "load") res = "laden";
        else if (id === "settings") res = "Einstellungen";
        else if (id === "run") res = "Programm starten";
        else if (id === "stop") res = "Programm stoppen";
        else if (id === "SR_LED") res = "LED {x} {y} {state}";
        else if (id === "SR_NOTE") res = "Note {index} {state}";
        else if (id === "SR_ON") res = "an";
        else if (id === "SR_OFF") res = "aus";
        else if (id === "C0") res = "bearbeiten";
        else if (id === "C1") res = "Beispiele";
        else if (id === "T10") res = "Seitenstart";
        else if (id === "T11") res = "drücken";
        else if (id === "T12") res = "loslassen";
        else if (id === "T13") res = "bewegen";
        else if (id === "T14") res = "Zeitmesser";
        else if (id === "T15") res = "Licht";
        else if (id === "T16") res = "Temperatur";
        else if (id === "T17") res = "Funkempfang";
        else if (id === "T18") res = "Geräusch";
        else if (id === "T19") res = "Variable X gesetzt";
        else if (id === "T20") res = "Variable Y gesetzt";
        else if (id === "T21") res = "Variable Z gesetzt";
        else if (id === "T22") res = "Magnet";
        else if (id === "T23") res = "Schieberegler";
        else if (id === "T24") res = "Drehschalter";
        else if (id === "T25") res = "Wand";
        else if (id === "T26") res = "Linie";
        else if (id === "T27") res = "Licht";
        else if (id === "T28") res = "Feuchtigkeit";
        else if (id === "T29") res = "Entfernung";
        else if (id === "T30") res = "Linie";
        else if (id === "T40") res = "Seite wechseln";
        else if (id === "T41") res = "Ton abspielen";
        else if (id === "T43") res = "Musik";
        else if (id === "T44") res = "Bild anzeigen";
        else if (id === "T45") res = "Nachricht über Funk senden";
        else if (id === "T46") res = "Funkgruppe setzen";
        else if (id === "T47") res = "RGB LEDs";
        else if (id === "T48") res = "setze Variable X";
        else if (id === "T49") res = "setze Variable Y";
        else if (id === "T50") res = "setze Variable Z";
        else if (id === "T51") res = "Nummer anzeigen";
        else if (id === "T52") res = "Roboter";
        else if (id === "T53") res = "Servo-Winkel einstellen";
        else if (id === "T54") res = "Relais";
        else if (id === "T55") res = "Servo-Leistung";
        else if (id === "T70") res = "Touch-Pin 0";
        else if (id === "T71") res = "Touch-Pin 1";
        else if (id === "T72") res = "Touch-Pin 2";
        else if (id === "T230") res = "Touch-Pin 3";
        else if (id === "T73") res = "Knopf A";
        else if (id === "T74") res = "Knopf B";
        else if (id === "T75") res = "Taste 1";
        else if (id === "T76") res = "Taste 2";
        else if (id === "T77") res = "Logo";
        else if (id === "T78") res = "1";
        else if (id === "T79") res = "2";
        else if (id === "T80") res = "3";
        else if (id === "T81") res = "4";
        else if (id === "T82") res = "5";
        else if (id === "T83") res = "1/4 Sekunde";
        else if (id === "T84") res = "1 Sekunde";
        else if (id === "T85") res = "1 zufällige Sekunde";
        else if (id === "T86") res = "5 Sekunden";
        else if (id === "T87") res = "laut";
        else if (id === "T88") res = "leise";
        else if (id === "T89") res = "nicht verfügbar";
        else if (id === "T90") res = "schütteln";
        else if (id === "T91") res = "nach oben kippen";
        else if (id === "T92") res = "nach unten kippen";
        else if (id === "T93") res = "nach links kippen";
        else if (id === "T94") res = "nach rechts kippen";
        else if (id === "T95") res = "Variable X";
        else if (id === "T96") res = "Variable Y";
        else if (id === "T97") res = "Variable Z";
        else if (id === "T98") res = "nach links drehen";
        else if (id === "T99") res = "nach rechts drehen";
        else if (id === "T100") res = "nach oben";
        else if (id === "T101") res = "nach unten";
        else if (id === "T103") res = "rechts";
        else if (id === "T104") res = "beide";
        else if (id === "T105") res = "nichts";
        else if (id === "T106") res = "links verloren";
        else if (id === "T107") res = "rechts verloren";
        else if (id === "T108") res = "Vorderseite nach oben";
        else if (id === "T109") res = "Vorderseite nach unten";
        else if (id === "T110") res = "an";
        else if (id === "T111") res = "aus";
        else if (id === "T150") res = "Seite 1";
        else if (id === "T151") res = "Seite 2";
        else if (id === "T152") res = "Seite 3";
        else if (id === "T153") res = "Seite 4";
        else if (id === "T154") res = "Seite 5";
        else if (id === "T155") res = "1";
        else if (id === "T156") res = "2";
        else if (id === "T157") res = "3";
        else if (id === "T158") res = "4";
        else if (id === "T159") res = "5";
        else if (id === "T160") res = "LED-Bild";
        else if (id === "T161") res = "rot";
        else if (id === "T162") res = "lila";
        else if (id === "T163") res = "kichern";
        else if (id === "T164") res = "fröhlich";
        else if (id === "T165") res = "Hallo";
        else if (id === "T166") res = "geheimnisvoll";
        else if (id === "T167") res = "traurig";
        else if (id === "T168") res = "gleiten";
        else if (id === "T169") res = "aufsteigend";
        else if (id === "T170") res = "Frühling";
        else if (id === "T171") res = "funkeln";
        else if (id === "T172") res = "gähnen";
        else if (id === "T173") res = "Variable X";
        else if (id === "T174") res = "Variable Y";
        else if (id === "T175") res = "Variable Z";
        else if (id === "T176") res = "Funkwert";
        else if (id === "T177") res = "Zufallszahl";
        else if (id === "T178") res = "wiederholen";
        else if (id === "T179") res = "Melodie";
        else if (id === "T180") res = "Temperatur";
        else if (id === "T181") res = "nicht verfügbar";
        else if (id === "T182") res = "rot";
        else if (id === "T183") res = "grün";
        else if (id === "T184") res = "blau";
        else if (id === "T185") res = "lila";
        else if (id === "T186") res = "gelb";
        else if (id === "T187") res = "schwarz";
        else if (id === "T188") res = "Regenbogen";
        else if (id === "T189") res = "funkeln";
        else if (id === "T190") res = "vorwärts";
        else if (id === "T191") res = "rückwärts";
        else if (id === "T192") res = "nach links drehen";
        else if (id === "T193") res = "nach rechts drehen";
        else if (id === "T194") res = "stoppen";
        else if (id === "T195") res = "schnell vorwärts";
        else if (id === "T196") res = "links drehen";
        else if (id === "T197") res = "rechts drehen";
        else if (id === "T198") res = "LED rot";
        else if (id === "T199") res = "LED grün";
        else if (id === "T200") res = "LED blau";
        else if (id === "T201") res = "LED AUS";
        else if (id === "T202") res = "Arm öffnen";
        else if (id === "T203") res = "Arm schließen";
        else if (id === "T204") res = "an";
        else if (id === "T205") res = "aus";
        else if (id === "T206") res = "Lichtwert";
        else if (id === "T207") res = "Magnetwert";
        else if (id === "T208") res = "Geräuschwert";
        else if (id === "T210") res = "addieren";
        else if (id === "T211") res = "subtrahieren";
        else if (id === "T212") res = "multiplizieren";
        else if (id === "T213") res = "dividieren";
        else if (id === "T214") res = "orange";
        else if (id === "T215") res = "rosa";
        else if (id === "T216") res = "türkis";
        else if (id === "T220") res = "gleich";
        else if (id === "T221") res = "nicht gleich";
        else if (id === "T222") res = "kleiner als";
        else if (id === "T223") res = "kleiner oder gleich";
        else if (id === "T224") res = "größer als";
        else if (id === "T225") res = "größer oder gleich";
        else if (id === "T255") res = "Zahl eingeben";        
        return res
    }
}